name: CI Pipeline

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
        r-version: [4.1]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r deployment/api/requirements.txt

      - name: Install R Dependencies
        run: |
          Rscript -e "install.packages(c('caret', 'glmnet', 'randomForest'), repos='https://cloud.r-project.org')"

  linting:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        r-version: [4.1]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint Python Code
        run: |
          pip install flake8
          flake8 .

      - name: Lint R Code
        run: |
          Rscript -e "lintr::lint_dir()"

  testing:
    needs: [setup, linting]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        r-version: [4.1]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Python Tests
        run: |
          pip install -r deployment/api/requirements.txt
          pytest

      - name: Run R Tests
        run: |
          Rscript -e "testthat::test_dir('tests/')"